# Permalinks
permalink:           pretty

# Setup
title:               'Starfleet Web'
tagline:             'Tricks & Tips & Tweaks'
description:         'Alcuni utili trucchetti per far funzionare le cose informatiche al timpano e dintorni'
url:                 'http://starfleetsns.github.io'
baseurl:             ''

# About/contact
author:
  name:              Starfleet crew
  email:             admin@starfleet.sns.it

# Default styles
defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "page"
