# Permalinks
permalink:           pretty

# Setup
title:               'Timpano'
tagline:             'Mas que un collegio'
description:         'Sito del Timpano'
url:                 'http://bianchis.starfleet.sns.it'
baseurl:             ''

# About/contact
author:
  name:              Dario Balboni
  email:             dario.balboni@sns.it

# Default styles
defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "page"
